mixed-port: 7890
allow-lan: true
mode: global

proxies:
  - name: VieFast-OSSH
    type: socks5
    server: 127.0.0.1
    port: 1080
    socks5-auth: false
    udp: true

proxy-groups:
  - name: Auto
    type: select
    proxies:
      - VieFast-OSSH

rules:
  - MATCH,Auto
